language: node_js
os:
  - linux
node_js:
  - 13

script:
  - cd books
  - npm install
  - npm run build
  - npm run webpack:production
  - cp -r dist/ ../docs
  - cd ..

cache: npm

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  cleanup: false
  on:
    branch: master
